INSERT INTO "property" VALUES (1, 3, NULL, 'РЕЕСТР', 'register', NULL);
INSERT INTO "property" VALUES (2, 4, NULL, 'РЕЕСТР Период внесения изменений', NULL, NULL);
INSERT INTO "property" VALUES (3, 2, NULL, 'Внесены изменения в Положение об ИОГВ', 'igov_changes', NULL);
INSERT INTO "property" VALUES (4, 2, NULL, 'Основание/ Дата внесения изменений в Положение (дата согласования КРИОГВ изменений в положение)', 'base_date_changes', NULL);
INSERT INTO "property" VALUES (5, 2, 6, 'Реквизиты НПА, которыми полномочие передано для осуществления ИОГВ субъекта РФ с федерального уровня', 'rekvisit_npa', NULL);
INSERT INTO "property" VALUES (6, 2, NULL, 'Полномочие осуществляется с использованием ИС', NULL, NULL);
INSERT INTO "property" VALUES (7, 2, 6, '№ пункта в положении об ИОГВ', 'punkt_iogv', NULL);
INSERT INTO "property" VALUES (8, 3, 6, 'Статус исполняемости', 'executable_status', NULL);
INSERT INTO "property" VALUES (9, 3, NULL, 'Услугу/функцию предоставляет Администрация района/ОМСУ/ФОИВ/ВФ/ГУ', NULL, NULL);
INSERT INTO "property" VALUES (10, 2, 6, 'Наименование ИОГВ СПб', 'name_iogv', NULL);
INSERT INTO "property" VALUES (11, 1, 6, 'id полномочия', 'id_authority', NULL);
INSERT INTO "property" VALUES (12, 1, 6, 'Статус согласования статуса полномочия', 'authority_status', NULL);
INSERT INTO "property" VALUES (13, 2, 6, 'Наименование полномочия в соответствии с Положением об ИОГВ', 'name_authority', NULL);
INSERT INTO "property" VALUES (14, 1, NULL, 'id государственной услуги/функции', 'id_service', NULL);
INSERT INTO "property" VALUES (15, 1, NULL, 'Статус разработки услуги/функции', 'service_status', NULL);
INSERT INTO "property" VALUES (16, 2, NULL, 'Наименование государственной функций (услуги) в соответствии с административным регламентом', 'service_name', NULL);
INSERT INTO "property" VALUES (17, 3, NULL, 'Тип', 'service_type', NULL);
INSERT INTO "property" VALUES (18, 3, NULL, 'субъект предоставления услуг (физ/юр)', 'service_subject', NULL);
INSERT INTO "property" VALUES (19, 2, NULL, '№ пункта Плана-графика 2013', NULL, NULL);
INSERT INTO "property" VALUES (20, 4, NULL, 'План-график 2013 (срок исполнения)', NULL, NULL);
INSERT INTO "property" VALUES (21, 2, NULL, 'План-график 2013 (требуется внесение изменений)', NULL, NULL);
INSERT INTO "property" VALUES (22, 2, NULL, 'Продление срока по Плану 2013', NULL, NULL);
INSERT INTO "property" VALUES (23, 2, NULL, 'Основание для продления срока по Плану 2013', NULL, NULL);
INSERT INTO "property" VALUES (24, 2, NULL, 'Исключение из Плана 2013', NULL, NULL);
INSERT INTO "property" VALUES (25, 2, NULL, 'Основание для исключения из Плана 2013', NULL, NULL);
INSERT INTO "property" VALUES (26, 3, NULL, 'План 2013 исполнен', NULL, NULL);
INSERT INTO "property" VALUES (27, 2, NULL, '№ пункта Плана-графика 2014', NULL, NULL);
INSERT INTO "property" VALUES (28, 4, NULL, 'Срок исполнения План-графика 2014', NULL, NULL);
INSERT INTO "property" VALUES (29, 2, NULL, 'Основание для включения услуги в План-график 2014', NULL, NULL);
INSERT INTO "property" VALUES (30, 2, NULL, 'Мониторинг в 2014 году', NULL, NULL);
INSERT INTO "property" VALUES (31, 2, NULL, 'Проведен мониторинг в 2013 году', NULL, NULL);
INSERT INTO "property" VALUES (32, 3, NULL, 'Услуга включена в дорожную карту ИОГВ', NULL, NULL);
INSERT INTO "property" VALUES (33, 2, NULL, '% удовлетворенности заявителей по услуге
', NULL, NULL);
INSERT INTO "property" VALUES (34, 2, NULL, '№ пункта Плана-графика 2012', NULL, NULL);
INSERT INTO "property" VALUES (35, 3, NULL, 'План-график 2012 (месяц)', NULL, NULL);
INSERT INTO "property" VALUES (36, 2, NULL, 'План-график 2012 Внесение изменений в АР', NULL, NULL);
INSERT INTO "property" VALUES (37, 2, NULL, 'Продление срока', NULL, NULL);
INSERT INTO "property" VALUES (38, 2, NULL, 'Исключение из Плана 2012', NULL, NULL);
INSERT INTO "property" VALUES (39, 2, NULL, 'Основание для исключения', NULL, NULL);
INSERT INTO "property" VALUES (40, 3, NULL, 'ПГ 2012 исполнен', NULL, NULL);
INSERT INTO "property" VALUES (41, 2, NULL, '1593', NULL, NULL);
INSERT INTO "property" VALUES (42, 2, NULL, '1593 (ред. от 20.09.2012)', NULL, NULL);
INSERT INTO "property" VALUES (43, 2, NULL, 'Внесение изменений в 1593', NULL, NULL);
INSERT INTO "property" VALUES (44, 2, NULL, 'Реквизиты соглашения', NULL, NULL);
INSERT INTO "property" VALUES (45, 2, NULL, 'Дата начала предоставления услуги в МФЦ', NULL, NULL);
INSERT INTO "property" VALUES (46, 2, NULL, 'Реализация в МАИС ЭГУ', NULL, NULL);
INSERT INTO "property" VALUES (47, 2, NULL, '8-рп', NULL, NULL);
INSERT INTO "property" VALUES (48, 2, NULL, 'Внесение изменений в 8-рп', NULL, NULL);
INSERT INTO "property" VALUES (49, 2, NULL, 'Реализация по ГК в 2014 году', NULL, NULL);
INSERT INTO "property" VALUES (50, 2, NULL, '11-рп от 13.03.2014', NULL, NULL);
INSERT INTO "property" VALUES (51, 5, NULL, 'этап предоставления на Портале', NULL, NULL);
INSERT INTO "property" VALUES (52, 3, NULL, 'Возможность выдачи результата в электронном виде', NULL, NULL);
INSERT INTO "property" VALUES (53, 2, NULL, 'УЭК', NULL, NULL);
INSERT INTO "property" VALUES (54, 2, NULL, 'Реализация на портале (Ростелеком)', NULL, NULL);
INSERT INTO "property" VALUES (55, 2, NULL, 'Актуализация по ЕПГУ', NULL, NULL);
INSERT INTO "property" VALUES (56, 2, NULL, '1993-р', NULL, NULL);
INSERT INTO "property" VALUES (57, 6, NULL, '729-р', NULL, NULL);
INSERT INTO "property" VALUES (58, 3, NULL, 'реализация в электронном виде', NULL, NULL);
INSERT INTO "property" VALUES (59, 2, NULL, '51-рп', NULL, NULL);
INSERT INTO "property" VALUES (60, 2, NULL, 'Внесение изменений в 51-рп', NULL, NULL);
INSERT INTO "property" VALUES (61, 2, NULL, 'ТКМВ (реквизиты  протокола РГ МИВ)', NULL, NULL);
INSERT INTO "property" VALUES (62, 2, NULL, 'ТКМВ внесение изменений (реквизиты  протокола РГ МИВ)', NULL, NULL);
INSERT INTO "property" VALUES (63, 2, NULL, 'КАР', NULL, NULL);
INSERT INTO "property" VALUES (64, 2, NULL, 'Административный регламент утвержден распоряжением ИОГВ', NULL, NULL);
INSERT INTO "property" VALUES (65, 2, NULL, 'Реквизиты нормативных правовых актов изменений в АР', NULL, NULL);
INSERT INTO "property" VALUES (66, 3, NULL, 'Возмездная / Безвозмездная государственная услуга', NULL, NULL);
INSERT INTO "property" VALUES (67, 2, NULL, 'Сумма госпошлины', NULL, NULL);
INSERT INTO "property" VALUES (68, 2, NULL, 'Количество взаимодействий ЮЛ и ИОГВ при предоставлении гос. услуги', NULL, NULL);
INSERT INTO "property" VALUES (69, 2, NULL, 'Наименование взаимодействий ЮЛ и ИОГВ при предоставлении гос. услуги', NULL, NULL);
INSERT INTO "property" VALUES (70, 2, NULL, 'Наименование услуги необходимой и обязательной, 
содержащейся в
постановлении
Правительства Санкт-Петербурга
от 03.02.2012 N 93', NULL, NULL);
INSERT INTO "property" VALUES (72, 4, 6, 'Cрок ответа', 'srok_otveta', NULL);
INSERT INTO "property" VALUES (73, 2, 7, 'Наименование услуги', 'sr_0', NULL);
INSERT INTO "property" VALUES (74, 2, 7, 'Краткое наименование услуги', 'sr_1', NULL);
INSERT INTO "property" VALUES (75, 2, 7, 'Наименование органов, участвующих в предоставлении услуги', 'sr_3', NULL);
INSERT INTO "property" VALUES (173, 3, 7, 'Сфера предоставления
Сфера предоставления
Сфера предоставления
Сфера предоставления', 'sr_2', NULL);
INSERT INTO "property" VALUES (174, 2, 7, 'Перечень НПА РФ, регулирующих предоставление услуги', 'sr_4', NULL);
INSERT INTO "property" VALUES (175, 2, 7, 'Перечень НПА СПб', 'sr_5', NULL);
INSERT INTO "property" VALUES (176, 2, 7, 'Способы предоставления услуги', 'sr_6', NULL);
INSERT INTO "property" VALUES (177, 2, 7, 'Результат предоставления услуги', 'sr_7', NULL);
INSERT INTO "property" VALUES (178, 2, 7, 'Тип заявителя', 'sr_9', NULL);
INSERT INTO "property" VALUES (179, 2, 7, 'Категория заявителей', 'sr_10', NULL);
INSERT INTO "property" VALUES (180, 2, 7, 'Сведения о местах, в которых можно получить информацию', 'sr_11', NULL);
INSERT INTO "property" VALUES (181, 2, 7, 'Срок предоставления', 'sr_8', NULL);
INSERT INTO "property" VALUES (182, 2, 7, 'Срок, в течение которого заявление должно быть зарегистрировано', 'sr_12', NULL);
INSERT INTO "property" VALUES (183, 2, 7, 'Максимальный срок ожидания в очереди', 'sr_13', NULL);
INSERT INTO "property" VALUES (184, 2, 7, 'Основания для приостановления предоставления либо отказа в предоставлении услуги (если возможность приостановления либо отказа в предоставлении услуги предусмотрена законодательством Российской Федерации)', 'sr_14', NULL);
INSERT INTO "property" VALUES (185, 2, 7, 'Перечень необходимых документов', 'sr_15', NULL);
INSERT INTO "property" VALUES (186, 2, 7, 'Способы получения этих документов (услуги, в результате которых можно получить документы)', 'sr_16', NULL);
INSERT INTO "property" VALUES (187, 2, 7, 'Сведения о возмездности услуги', 'sr_17', NULL);
INSERT INTO "property" VALUES (188, 2, 7, 'Стоимость услуги', 'sr_18', NULL);
INSERT INTO "property" VALUES (189, 2, 7, 'Показатели доступности и качества услуги', 'sr_19', NULL);
INSERT INTO "property" VALUES (190, 2, 7, 'Информация о внутриведомственных и межведомственных процедурах', 'sr_20', NULL);
INSERT INTO "property" VALUES (191, 2, 7, 'Сведения о допустимости (возможности) и порядке досудебного (внесудебного) обжалования решений и действий (бездействия) органа, учреждения (организации), предоставляющего услугу', 'sr_21', NULL);
INSERT INTO "property" VALUES (192, 2, 7, 'Наличие межведомственного взаимодействия', 'sr_22', NULL);
INSERT INTO "property" VALUES (193, 2, 7, 'Технологическая карта межведомственного взаимодействия (при наличии межведомственного взаимодействия с федеральными органами исполнительной власти, органами государственных внебюджетных фондов, органами исполнительной власти субъектов Российской Федерации, органами местного самоуправления, учреждениями (организациями), участвующими в оказании услуги)', 'sr_23', NULL);
